// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package registration

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegisterClient is the client API for Register service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterClient interface {
	RegistrationRequest(ctx context.Context, in *Registration, opts ...grpc.CallOption) (*Reply, error)
	MonitorSession(ctx context.Context, opts ...grpc.CallOption) (Register_MonitorSessionClient, error)
}

type registerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterClient(cc grpc.ClientConnInterface) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) RegistrationRequest(ctx context.Context, in *Registration, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/registration.Register/RegistrationRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) MonitorSession(ctx context.Context, opts ...grpc.CallOption) (Register_MonitorSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Register_ServiceDesc.Streams[0], "/registration.Register/MonitorSession", opts...)
	if err != nil {
		return nil, err
	}
	x := &registerMonitorSessionClient{stream}
	return x, nil
}

type Register_MonitorSessionClient interface {
	Send(*MonitorMessage) error
	Recv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type registerMonitorSessionClient struct {
	grpc.ClientStream
}

func (x *registerMonitorSessionClient) Send(m *MonitorMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *registerMonitorSessionClient) Recv() (*emptypb.Empty, error) {
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RegisterServer is the server API for Register service.
// All implementations must embed UnimplementedRegisterServer
// for forward compatibility
type RegisterServer interface {
	RegistrationRequest(context.Context, *Registration) (*Reply, error)
	MonitorSession(Register_MonitorSessionServer) error
	mustEmbedUnimplementedRegisterServer()
}

// UnimplementedRegisterServer must be embedded to have forward compatible implementations.
type UnimplementedRegisterServer struct {
}

func (UnimplementedRegisterServer) RegistrationRequest(context.Context, *Registration) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrationRequest not implemented")
}
func (UnimplementedRegisterServer) MonitorSession(Register_MonitorSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitorSession not implemented")
}
func (UnimplementedRegisterServer) mustEmbedUnimplementedRegisterServer() {}

// UnsafeRegisterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterServer will
// result in compilation errors.
type UnsafeRegisterServer interface {
	mustEmbedUnimplementedRegisterServer()
}

func RegisterRegisterServer(s grpc.ServiceRegistrar, srv RegisterServer) {
	s.RegisterService(&Register_ServiceDesc, srv)
}

func _Register_RegistrationRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).RegistrationRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registration.Register/RegistrationRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).RegistrationRequest(ctx, req.(*Registration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_MonitorSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RegisterServer).MonitorSession(&registerMonitorSessionServer{stream})
}

type Register_MonitorSessionServer interface {
	Send(*emptypb.Empty) error
	Recv() (*MonitorMessage, error)
	grpc.ServerStream
}

type registerMonitorSessionServer struct {
	grpc.ServerStream
}

func (x *registerMonitorSessionServer) Send(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *registerMonitorSessionServer) Recv() (*MonitorMessage, error) {
	m := new(MonitorMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Register_ServiceDesc is the grpc.ServiceDesc for Register service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Register_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registration.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistrationRequest",
			Handler:    _Register_RegistrationRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorSession",
			Handler:       _Register_MonitorSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "registration.proto",
}
