// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configuration.proto

package configuration

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Function int32

const (
	Function_PTAGENT     Function = 0
	Function_PTCOLLECTOR Function = 1
	Function_PTRECORDER  Function = 2
)

var Function_name = map[int32]string{
	0: "PTAGENT",
	1: "PTCOLLECTOR",
	2: "PTRECORDER",
}

var Function_value = map[string]int32{
	"PTAGENT":     0,
	"PTCOLLECTOR": 1,
	"PTRECORDER":  2,
}

func (x Function) String() string {
	return proto.EnumName(Function_name, int32(x))
}

func (Function) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{0}
}

type Mode int32

const (
	Mode_PNODE  Mode = 0
	Mode_PENODE Mode = 1
)

var Mode_name = map[int32]string{
	0: "PNODE",
	1: "PENODE",
}

var Mode_value = map[string]int32{
	"PNODE":  0,
	"PENODE": 1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{1}
}

type ReturnCode int32

const (
	ReturnCode_OK    ReturnCode = 0
	ReturnCode_ERRID ReturnCode = 1
)

var ReturnCode_name = map[int32]string{
	0: "OK",
	1: "ERRID",
}

var ReturnCode_value = map[string]int32{
	"OK":    0,
	"ERRID": 1,
}

func (x ReturnCode) String() string {
	return proto.EnumName(ReturnCode_name, int32(x))
}

func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{2}
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Function             Function `protobuf:"varint,3,opt,name=function,proto3,enum=configuration.Function" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Request) GetFunction() Function {
	if m != nil {
		return m.Function
	}
	return Function_PTAGENT
}

type Reply struct {
	Id                   []byte            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReturnCode           ReturnCode        `protobuf:"varint,2,opt,name=return_code,json=returnCode,proto3,enum=configuration.ReturnCode" json:"return_code,omitempty"`
	ErrorDetail          string            `protobuf:"bytes,3,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	Mode                 Mode              `protobuf:"varint,4,opt,name=mode,proto3,enum=configuration.Mode" json:"mode,omitempty"`
	Ports                map[string]uint32 `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Reply) GetReturnCode() ReturnCode {
	if m != nil {
		return m.ReturnCode
	}
	return ReturnCode_OK
}

func (m *Reply) GetErrorDetail() string {
	if m != nil {
		return m.ErrorDetail
	}
	return ""
}

func (m *Reply) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_PNODE
}

func (m *Reply) GetPorts() map[string]uint32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func init() {
	proto.RegisterEnum("configuration.Function", Function_name, Function_value)
	proto.RegisterEnum("configuration.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("configuration.ReturnCode", ReturnCode_name, ReturnCode_value)
	proto.RegisterType((*Request)(nil), "configuration.Request")
	proto.RegisterType((*Reply)(nil), "configuration.Reply")
	proto.RegisterMapType((map[string]uint32)(nil), "configuration.Reply.PortsEntry")
}

func init() { proto.RegisterFile("configuration.proto", fileDescriptor_415c9e57263f32ab) }

var fileDescriptor_415c9e57263f32ab = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0x3a, 0x71, 0xda, 0x8c, 0xd3, 0xd4, 0x4c, 0x23, 0x08, 0x95, 0x50, 0x4d, 0x2f, 0x58,
	0x39, 0xf8, 0xe0, 0x0a, 0x29, 0x2a, 0x27, 0xb0, 0x17, 0x84, 0x28, 0xb5, 0x35, 0xf2, 0x89, 0x4b,
	0xe5, 0xc6, 0x5b, 0x64, 0xe1, 0x7a, 0xcd, 0xd6, 0x46, 0xf2, 0x5f, 0xf0, 0xc9, 0xc8, 0x9b, 0xd4,
	0x25, 0x6d, 0x6f, 0x6f, 0xdf, 0xbc, 0x7d, 0x33, 0xf3, 0x34, 0x70, 0xb4, 0x96, 0xe5, 0x4d, 0xfe,
	0xb3, 0x51, 0x69, 0x9d, 0xcb, 0xd2, 0xab, 0x94, 0xac, 0x25, 0x1e, 0xec, 0x90, 0xa7, 0xd7, 0xb0,
	0x47, 0xe2, 0x77, 0x23, 0xee, 0x6a, 0x44, 0x18, 0x95, 0xe9, 0xad, 0x58, 0x30, 0x87, 0xb9, 0x13,
	0xd2, 0x18, 0x67, 0x60, 0xe4, 0xd9, 0xc2, 0x70, 0x98, 0x3b, 0x25, 0x23, 0xcf, 0xf0, 0x0c, 0xf6,
	0x6f, 0x9a, 0x72, 0xdd, 0x7d, 0x5d, 0x0c, 0x1d, 0xe6, 0xce, 0xfc, 0x57, 0xde, 0x6e, 0x97, 0xcf,
	0xdb, 0x32, 0xf5, 0xc2, 0xd3, 0xbf, 0x06, 0x98, 0x24, 0xaa, 0xa2, 0xdd, 0xda, 0xb1, 0xde, 0xee,
	0x1c, 0x2c, 0x25, 0xea, 0x46, 0x95, 0x57, 0x6b, 0x99, 0x09, 0xdd, 0x67, 0xe6, 0xbf, 0x7e, 0xe4,
	0x48, 0x5a, 0x11, 0xc8, 0x4c, 0x10, 0xa8, 0x1e, 0xe3, 0x5b, 0x98, 0x0a, 0xa5, 0xa4, 0xba, 0xca,
	0x44, 0x9d, 0xe6, 0x85, 0x1e, 0x67, 0x42, 0x96, 0xe6, 0x42, 0x4d, 0xe1, 0x3b, 0x18, 0xdd, 0x76,
	0xbe, 0x23, 0xed, 0x7b, 0xf4, 0xc8, 0xf7, 0x7b, 0xe7, 0xa8, 0x05, 0xf8, 0x1e, 0xcc, 0x4a, 0xaa,
	0xfa, 0x6e, 0x61, 0x3a, 0x43, 0xd7, 0xf2, 0x4f, 0x9e, 0x4c, 0x50, 0x15, 0xad, 0x17, 0x77, 0x0a,
	0x5e, 0xd6, 0xaa, 0xa5, 0x8d, 0xfa, 0x78, 0x05, 0xf0, 0x40, 0xa2, 0x0d, 0xc3, 0x5f, 0xa2, 0xdd,
	0xc6, 0xd7, 0x41, 0x9c, 0x83, 0xf9, 0x27, 0x2d, 0x9a, 0xcd, 0x62, 0x07, 0xb4, 0x79, 0x9c, 0x1b,
	0x2b, 0xb6, 0x5c, 0xc1, 0xfe, 0x7d, 0x50, 0x68, 0xc1, 0x5e, 0x9c, 0x7c, 0xfc, 0xc2, 0x2f, 0x13,
	0x7b, 0x80, 0x87, 0x60, 0xc5, 0x49, 0x10, 0x5d, 0x5c, 0xf0, 0x20, 0x89, 0xc8, 0x66, 0x38, 0x03,
	0x88, 0x13, 0xe2, 0x41, 0x44, 0x21, 0x27, 0xdb, 0x58, 0xbe, 0x81, 0x51, 0x37, 0x38, 0x4e, 0xc0,
	0x8c, 0x2f, 0xa3, 0x90, 0xdb, 0x03, 0x04, 0x18, 0xc7, 0x5c, 0x63, 0xb6, 0x3c, 0x01, 0x78, 0xc8,
	0x0b, 0xc7, 0x60, 0x44, 0xdf, 0xec, 0x41, 0x27, 0xe6, 0x44, 0x5f, 0x43, 0x9b, 0xf9, 0x09, 0x4c,
	0x83, 0x7e, 0x39, 0xa9, 0x30, 0x84, 0x79, 0xf0, 0xff, 0xb2, 0xf7, 0xd7, 0xf0, 0xf2, 0x49, 0x06,
	0x9a, 0x3f, 0x9e, 0x3f, 0x97, 0xcd, 0xa7, 0x17, 0x3f, 0x0e, 0xbd, 0x0f, 0x3b, 0x85, 0xeb, 0xb1,
	0xbe, 0xb7, 0xb3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x64, 0x0b, 0x39, 0x86, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfiguratorClient is the client API for Configurator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfiguratorClient interface {
	ConfigurationRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type configuratorClient struct {
	cc *grpc.ClientConn
}

func NewConfiguratorClient(cc *grpc.ClientConn) ConfiguratorClient {
	return &configuratorClient{cc}
}

func (c *configuratorClient) ConfigurationRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/configuration.Configurator/ConfigurationRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfiguratorServer is the server API for Configurator service.
type ConfiguratorServer interface {
	ConfigurationRequest(context.Context, *Request) (*Reply, error)
}

// UnimplementedConfiguratorServer can be embedded to have forward compatible implementations.
type UnimplementedConfiguratorServer struct {
}

func (*UnimplementedConfiguratorServer) ConfigurationRequest(ctx context.Context, req *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigurationRequest not implemented")
}

func RegisterConfiguratorServer(s *grpc.Server, srv ConfiguratorServer) {
	s.RegisterService(&_Configurator_serviceDesc, srv)
}

func _Configurator_ConfigurationRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfiguratorServer).ConfigurationRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configuration.Configurator/ConfigurationRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfiguratorServer).ConfigurationRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Configurator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "configuration.Configurator",
	HandlerType: (*ConfiguratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigurationRequest",
			Handler:    _Configurator_ConfigurationRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configuration.proto",
}
